In [1]:
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA
import numpy as np

In [2]:
iris = load_iris()
X = iris["data"]

In [14]:
X_centered = X - X.mean(axis=0)
U, s, Vt = np.linalg.svd(X_centered)
c1 = Vt.T[:, 0]
c2 = Vt.T[:, 1]
W2 = Vt.T[:, :2]
X2D_svd = X_centered.dot(W2)  ## Beware of the transpose !!

In [19]:
np.dot(U, np.diag(s))

ValueError: shapes (150,150) and (4,4) not aligned: 150 (dim 1) != 4 (dim 0)

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 2)
X2D_pca = pca.fit_transform(X)

In [12]:
##  Vectors
pca.components_.T

array([[ 0.36138659,  0.65658877],
       [-0.08452251,  0.73016143],
       [ 0.85667061, -0.17337266],
       [ 0.3582892 , -0.07548102]])

In [13]:
v.T[:, :2]

array([[ 0.36138659, -0.65658877],
       [-0.08452251, -0.73016143],
       [ 0.85667061,  0.17337266],
       [ 0.3582892 ,  0.07548102]])

In [16]:
n, m = X.shape
C = np.dot(X_centered.T, X_centered) / (n-1)
# Eigen decomposition
eigen_vals, eigen_vecs = np.linalg.eig(C)
# Project X onto PC space
X_pca = np.dot(X_centered, eigen_vecs)

In [17]:
eigen_vecs

array([[ 0.36138659, -0.65658877, -0.58202985,  0.31548719],
       [-0.08452251, -0.73016143,  0.59791083, -0.3197231 ],
       [ 0.85667061,  0.17337266,  0.07623608, -0.47983899],
       [ 0.3582892 ,  0.07548102,  0.54583143,  0.75365743]])